# Generated by Django 3.2.7 on 2021-11-25 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('Highest_Qualification', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('bio', models.TextField(max_length=1000)),
                ('Profile_Photo', models.ImageField(blank=True, null=True, upload_to='static/profile_pic')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
