# Generated by Django 3.0.5 on 2021-11-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0002_auto_20211125_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database_user',
            old_name='Highest_Qualification',
            new_name='highest_qualification',
        ),
        migrations.RenameField(
            model_name='database_user',
            old_name='Profile_Photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='database_user',
            old_name='User',
            new_name='user',
        ),
    ]
