# Generated by Django 3.0.5 on 2021-11-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0004_auto_20211126_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
