# Generated by Django 3.0.5 on 2021-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0006_auto_20211126_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='database_user',
            name='DP',
            field=models.URLField(null=True),
        ),
    ]
