# Generated by Django 3.0.5 on 2021-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0007_database_user_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_user',
            name='DP',
            field=models.URLField(blank=True, null=True),
        ),
    ]
