# Generated by Django 3.0.5 on 2021-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0008_auto_20211127_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='database_user',
            name='image_dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
