# Generated by Django 3.0.5 on 2021-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0009_database_user_image_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database_user',
            name='DP',
        ),
        migrations.RemoveField(
            model_name='database_user',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='database_user',
            name='gender',
            field=models.CharField(default='Gender', max_length=50),
        ),
    ]
