# Generated by Django 5.0.1 on 2024-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0010_auto_20211209_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
